### ISSUE TITLE
Please add booktoki157.com

### ISSUE THREAD

**Issue by MoonGoblinDev** [gmastergreatee/LightNovel-Manager#11]
URL : booktoki157.com
Novel Example : https://booktoki157.com/novel/2549988?stx=%EC%82%AC%EC%8B%A0%ED%91%9C%EC%9B%94

It's a korean raw novel site, I struggle creating my own rule. Hope someone can help!

**Comment by MoonGoblinDev** [comment]
I somehow able to create my own rules. Closed

**Comment by gmastergreatee** [comment]
Great! Feel free to request for any english website inclusion.

It will be a lil hard for me to check through websites with non-English content.
