### ISSUE TITLE
Royalroad.com rule issue.

### ISSUE THREAD

**Issue by AbanobNageh** [gmastergreatee/LightNovel-Manager#16]
**Describe the bug**
Hello, first I wanted to thank you for this manager, I like using it to keep all stories I read in one place.
Next, I wanted to report that there seems to be an issue with the rule for `royalroad.com`. When I try to update or download specific stories they download up to a certain chapter before the downloading stops. The story still shows as downloading but nothing actually happens.

I can reproduce this with 2 stories, they are:
- https://www.royalroad.com/fiction/21410/super-minion
- https://www.royalroad.com/fiction/66546/alpha-strike-an-interstellar-weapon-platforms

At the time of writing this issue the first stops at 61/62 chapters and the second stops at 116/118 chapters.

**To Reproduce**
1. Add either of the above stories (or directly move to the second step if either already exists).
2. Once they are added click on the download button.
3. It should stop downloading and clicking stop causes all the buttons for the novel to be disabled.

**Expected behavior**
The story should download normally.

**Screenshots**

Before clicking the download button for an already existing story:
![image](https://github.com/gmastergreatee/Fanfiction-Manager/assets/22684921/e4d7647d-9d86-438a-859e-4b9afe311b46)

After clicking download, this is how the story will look like until I close and reopen the manager:
![image](https://github.com/gmastergreatee/Fanfiction-Manager/assets/22684921/ed2967d5-5894-430b-8233-50218df02312)
![image](https://github.com/gmastergreatee/Fanfiction-Manager/assets/22684921/08879765-1d6c-4d40-9edd-cba9db0ba844)

If I click stop:
![image](https://github.com/gmastergreatee/Fanfiction-Manager/assets/22684921/5a19d529-bb1f-4899-9d0f-18b2749f8c82)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 120.0.6099.217 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by gmastergreatee** [comment]
Thanks for reporting. Will check asap!

**Comment by gmastergreatee** [comment]
Need to change the rule a lil bit

In the `URL Blocks` section

Remove the line `amazon` and it should work
Will update the rule shortly

Thanks again
