### ISSUE TITLE
Webnovel.com not working??

### ISSUE THREAD

**Issue by hunghungtre** [gmastergreatee/LightNovel-Manager#18]
this is what i get when trying to download something from webnovel.com is there a soulation? 
Error -> [SCRIPT] Cannot read properties of null (reading 'value')

**Comment by gmastergreatee** [comment]
Please also provide the link where you faced this issue

**Comment by gmastergreatee** [comment]
On my side all seems to be fine, and the fanfiction download seems to be working

![fanfiction-manager-test_18](https://github.com/gmastergreatee/Fanfiction-Manager/assets/91471329/75ed5191-739e-4acf-b93d-305398b0103a)

From the info that is provided, I'm unable to find out the exact issue on your side. Seeing that the WebNovel related rule was last modified 2 years ago https://github.com/gmastergreatee/Fanfiction-Manager/commit/c12df32b51948fdc20bad25d322fb7ddab7ecf79 , so trying to fix by updating the rules is unlikely to work.

Please provide more info, viz. maybe show whats actually happening by attaching a gif file here. There are multiple gif recorders out there. I use LICEcap though, simple and easy. Make sure the FPS is > 10FPS

**Comment by gmastergreatee** [comment]
Please update Rules and check, maybe fa0bf0fe2b89e5461919ebf707f0e91308287818 also fixed your issue
