### ISSUE TITLE
UpdateDownloadAll, and sometimes normal update on single novel has issues with getting chapter list

### ISSUE THREAD

**Issue by AurelionSoldMe** [gmastergreatee/LightNovel-Manager#19]
**Describe the bug**

UpdateDownloadAll, and sometimes normal update on single novel has issues with getting chapter list

Not sure of the cause, works well when you test the effected novel in the rule tester, but on main page the functions sometimes do not perform the same (ex: updated novel on main list shows 500/500, go to the rule tester throw the novel in you can get 512 ch found

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] beta 3.1.9

**Additional context**

Would label this really low prio, if it really needs to be addressed cause it could be a issue of a rule slamming a site, or enforced cache (Cloudflare)

**Comment by gmastergreatee** [comment]
Yes the UpdateDownloadAll button has issues, its being tracked in #13 . To fix this, the way how novels are downloaded/updated needs to be changed. I've it on mind but would require a drastic effort.

Currently I'm waiting for tauri to get to a stable android publish version and support all required features. Then I'll develop another application which will work cross-platform.

Send me the link of novel which you mentioned above, getting 500 chaps in library but 512 in tester. I'll check.

**Comment by AurelionSoldMe** [comment]
https://novelmax.net/n/kill-the-sun#tab-chapters-title

Is the link, sometime it finds it sometimes it does not, as for the updatedownloadall I will see if I can hack / Band-Aid a solution for it, and I will share the code of it later but if I do just a heads up my client is wonky all over due to me adding a broken api to it. 

(my experience with working with UI's is 0)

**Comment by AurelionSoldMe** [comment]
Going to close this since there is a earlier ticket

https://github.com/gmastergreatee/Fanfiction-Manager/issues/13
