### ISSUE TITLE
Does not work on linux/crostini/archlinux.

### ISSUE THREAD

**Issue by lavilao** [gmastergreatee/LightNovel-Manager#21]
**Describe the bug**
Tried with the default electron package from archlinux (electron 30), electron 23, electron 19 from aur and finally with the electron 19 from the readme, in each of the attempts it crashed with 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'follow-redirects'
```

**To Reproduce**
follow the readme instructions for others on linux

**Expected behavior**
the application should open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: chromeos
 - Browser chrome
 - Version 123

**Additional context**

**Comment by AurelionSoldMe** [comment]
Path into the project folder and run:

npm install follow-redirects

Had the same issue a little go, sometimes my OS had it other times not.

**Comment by lavilao** [comment]
the error is gone after installing follow-redirects and extract-zip on the app/ folder but when executing electron it just shows a black screen (like when opening index.html with chrome).

**Comment by AurelionSoldMe** [comment]
Sounds like the zip is wonked, I uploaded what should be the core files from the UI (everything but my data, and config folders)
[app.zip](https://github.com/gmastergreatee/Fanfiction-Manager/files/15181266/app.zip)

You can just extract and overwrite and it should turn out fine

**Comment by lavilao** [comment]
Thanks! it works with electron 19

**Comment by gmastergreatee** [comment]
Oh, seems I forgot adding the `node_modules` folder in the `app.zip` mentioned in the [Download Instructions](https://github.com/gmastergreatee/Fanfiction-Manager#download)

Thank you very much for reporting, will include it in the initial package.
