### ISSUE TITLE
The "novelmax | binnovel" TOC script doesn't work.

### ISSUE THREAD

**Issue by AbanobNageh** [gmastergreatee/LightNovel-Manager#22]
**Describe the bug**
The "novelmax | binnovel" TOC script currently doesn't work. It gives the following error:

```
Error -> [SCRIPT] ajaxChapterArchiveUrl is not defined
```

**To Reproduce**
1. Open the "novelmax | binnovel" rule.
2. Add the following test URL: https://novelmax.net/n/getting-a-technology-system-in-modern-day
3. Load the URL and then try to run the TOC script.
4. See the error in the console.

**Expected behavior**
The rule should work correctly like it did before.

**Screenshots**
Here is how it looks like If I try to test it in the app:
![image](https://github.com/gmastergreatee/Fanfiction-Manager/assets/22684921/0d8008b1-e129-43c4-b33b-fd0ba988c68b)

**Desktop (please complete the following information):**
 - OS: Windows 10.

**Additional context**
N/A

**Comment by gmastergreatee** [comment]
@AbanobNageh plz check and report if still not working

**Comment by AbanobNageh** [comment]
It is working correctly now. Thank you. 👍
