### ISSUE TITLE
Allow Renderer interaction while loading

### ISSUE THREAD

**Issue by gmastergreatee** [gmastergreatee/LightNovel-Manager#5]
Currently all renderer actions are blocked.

Need to give the choice to the user if one wants to or not.

- [ ] Option for activating/deactivating user interaction in the renderer

**Comment by kolbdog3333** [comment]
No would never use it

**Comment by gmastergreatee** [comment]
@kolbdog3333 this will be required in case there's a manual captcha, or while testing new/existing rules

**Comment by gmastergreatee** [comment]
Release now available
